aws_access_key: AKIATZLRUKZ53H5MRCZF
aws_private_key: Csuv3pDkwsM58OZyDg65IhEmWqdNhKdPdBsjsnHi
aws_bucket: bagguimgbucket

env_staticDir: /src/main/resources/static/files/

jwt_secret_key: jwt-temp-secret-key