aws_access_key: AKIATZLRUKZ5XO4IBUXQ
aws_private_key: X+DPyXyF+6BMv81o0hW3hNQ8pMmfop14cK55x2Fr
aws_bucket: bagguimgbucket

env_staticDir: /src/main/resources/static/files/

jwt_secret_key: jwt-temp-secret-key