aws_access_key: AKIATUJNMGMY47ABRKUF
aws_private_key: VRE/rxT8PxdRQ6s/qLaqmQL0H421gjZJvYB8C+fU
aws_bucket: bagguimg

#백엔드를 로컬에서 돌릴 경우
env_staticDir: /src/main/resources/static/

#백엔드를 서버에서 돌릴 경우
#env_staticDir: /app/s3/temp

jwt_secret_key: jwt-temp-secret-key