aws_access_key: AKIATZLRUKZ55LNBJDWL
aws_private_key: GwOYysJ7SwvaTswyBWbT1KcwgFOR2O+qp4HIfYZA
aws_bucket: bagguimgbucket

env_staticDir: /src/main/resources/static/files/

jwt_secret_key: jwt-temp-secret-key