aws_access_key: AKIATUJNMGMY47ABRKUF
aws_private_key: VRE/rxT8PxdRQ6s/qLaqmQL0H421gjZJvYB8C+fU
aws_bucket: bagguimg

# 백엔드 로컬 테스트용
# env_staticDir: /src/main/resources/static/

# 서버용
env_staticDir: /app/s3/temp

jwt_secret_key: jwt-temp-secret-key

redis:
  host: 127.0.0.1
  port: 6379
  password: 8B4FEDDBD6709F57F46AADAAB0E18CDA964413A4208D828C7D68B3E7028DE0E6758C9C85A71AD65F8B5D36727CB1DEBF33E854486BEBEACEE0344200887C52CB